### ISSUE TITLE
README.md needs an update

### ISSUE THREAD

**Issue by Achie72** [Achie72/crazy_rabbit_afternoon#19]
A better update could be used for much better presentation.
See example in [Neon Runner](https://github.com/Achie72/neon-runner)

Image could be grabbed from the [itch.io](https://achie.itch.io/crazy-rabbit-afternoon) site with:

`![alt text](link)` format

---

Moreover the already long README.md could be split up into a `DESIGN.md` and a short `README.md` linking to all others.

**Comment by kisbg** [comment]
Hi Achie72 ! I created a pull request based on the issue :)
 #20
